DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
  id VARCHAR(36) DEFAULT CAST(RANDOM_UUID() AS VARCHAR(36)) PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description CLOB,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status VARCHAR(32) NOT NULL
);
